//dummyGroups data used for testing UserGroupBar component
const dummyGroups = [
    {
      type: "Course",
      status: "Available",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 6,
      minMember: 5,
      currentMember: 4,
      title: "Hey, CS732 need members here! we are going to develop a very cooooooool stuff",
      content: "We already have a project topic, we still need a tester",
      tags: ["React", "MongoDB", "COMPSCI732"],
    },
    {
      type: "Activity",
      status: "Full",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 6,
      minMember: 6,
      currentMember: 6,
      title: "Hiking Trip",
      content:
        "Join us for a fun hiking trip to Mount XYZ. All skill levels welcome!",
      tags: ["Outdoor", "Hiking", "Nature"],
    },
    {
      type: "Course",
      status: "Closed",
      deadlineDate: "0 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 10,
      minMember: 8,
      currentMember: 9,
      title: "Introduction to Python Programming",
      content:
        "Learn Python programming language from scratch. No prior experience required.",
      tags: ["Python", "Programming", "COMPSCI732"],
    },
    {
      type: "Activity",
      status: "Available",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 10,
      minMember: 8,
      currentMember: 9,
      title: "Board Game Night",
      content: "Join us for a night of fun board games and friendly competition.",
      tags: ["Board Games", "Social", "Fun"],
    },
    {
      type: "Course",
      status: "Full",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 8,
      minMember: 6,
      currentMember: 8,
      title: "Advanced JavaScript Workshop",
      content:
        "Take your JavaScript skills to the next level with this advanced workshop.",
      tags: ["JavaScript", "Advanced", "Workshop"],
    },
    {
      type: "Activity",
      status: "Closed",
      deadlineDate: "0 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 8,
      minMember: 8,
      currentMember: 4,
      title: "Cooking Class",
      content:
        "Learn to cook delicious meals from expert chefs. Limited spots available.",
      tags: ["Cooking", "Class", "Food"],
    },
    {
      type: "Course",
      status: "Available",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 15,
      minMember: 10,
      currentMember: 7,
      title: "Data Science Bootcamp",
      content:
        "Join our comprehensive data science bootcamp and kickstart your career.",
      tags: ["DataScience", "Bootcamp", "Career"],
    },
    {
      type: "Activity",
      status: "Full",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 15,
      minMember: 15,
      currentMember: 15,
      title: "Yoga Session",
      content: "Relax your mind and body with our yoga session. Mats provided.",
      tags: ["Yoga", "Relaxation", "Health"],
    },
    {
      type: "Course",
      status: "Closed",
      deadlineDate: "0 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 20,
      minMember: 15,
      currentMember: 20,
      title: "Artificial Intelligence Masterclass",
      content:
        "Explore the latest advancements in AI technology in this masterclass.",
      tags: ["AI", "Masterclass", "Technology"],
    },
    {
      type: "Activity",
      status: "Available",
      deadlineDate: "1 day left",
      owner:"rainman96",
      avatar:"https://www.animesenpai.net/wp-content/uploads/2022/12/Bocchi-The-Rock-21-1024x576.webp",
      maxMember: 20,
      minMember: 15,
      currentMember: 15,
      title: "Photography Workshop",
      content:
        "Learn photography techniques from professional photographers. Bring your camera!",
      tags: ["Photography", "Workshop", "Skills"],
    },
  ];
  
 export default dummyGroups;